### ISSUE TITLE
No "BitBucket" entry in "Security" menu

### ISSUE THREAD

**Issue by dbac2002** [SonarQubeCommunity/sonar-auth-bitbucket#4]
Hi,

I have sonarqube 5.6 with the plugin v1.0.

Based on the readme there should be

> Go to "Security" -> "Bitbucket"

But my Security menu, has no Bitbucket entry 

![sonarqube-bitbucket](https://cloud.githubusercontent.com/assets/16955305/15856604/d2d80d22-2cb6-11e6-883c-471893dfde01.png)

what do I miss ?

**Comment by simonbrandhof** [comment]
It is in settings page (Administration > Configuration > General Settings > Security)
