### ISSUE TITLE
Infobox shows invalid callback url

### ISSUE THREAD

**Issue by etki** [SonarQubeCommunity/sonar-auth-bitbucket#6]
Hey,

I've tried plugin today with a little hassle: configuration box shows that callback url is `<installation uri>/oauth2/callback` while in reality it was `<installation uri>/oauth2/callback/bitbucket`. This may be related to sonarqube itself, since github plugin behaves the same.

![sonarqube-bitbucket-plugin-issue](https://cloud.githubusercontent.com/assets/1909762/19888789/f6eaec58-a041-11e6-9dea-99d977145d90.png)

**Comment by julienlancelot** [comment]
I confirm that the callback url should be <installation uri>/oauth2/callback.
What happen when you're using this URL ?

**Comment by etki** [comment]
@julienlancelot i'm feeling like i've stumbled upon a heisenbug. Everything works both with `/oauth2/callback` and `/oauth2/callback/bitbucket` today, so **it's not reproducing today**. I've got two problems yesterday:

- Atlassian wouldn't let me finish login without because of "invalid redirect_uri" (and as far as i remember i've checked that https scheme is in place and uri is not malformed - that could be dns problems that resolved later)
- "You're not authorized to access this page. Please contact the administrator." (for both github oauth plugin and bitbucket oauth plugin)

After that i've googled down steven-turner/sonar-auth-google#1 issue, saw `/google` endpoint and tried the same with github and bitbucket, and then it just started working. Also i've seen it in source code: https://github.com/SonarSource/sonarqube/search?utf8=%E2%9C%93&q=oauth2%2Fcallback%2Fgithub

**Comment by julienlancelot** [comment]
Ok, it's strange, but it's good that now working with /oauth2/callback.
I'm then closing this issue.
