### ISSUE TITLE
Hosted bitbucket server

### ISSUE THREAD

**Issue by sachingharge** [SonarQubeCommunity/sonar-auth-bitbucket#8]
Hi Team,

Can we use this plugin with hosted bitbucket server for authentication?

**Comment by julienlancelot** [comment]
Hi,

It's not possible for the moment, but it should not be too complex as it only require to make the setting "sonar.auth.bitbucket.apiUrl" (https://github.com/SonarQubeCommunity/sonar-auth-bitbucket/blob/master/src/main/java/org/sonarqube/auth/bitbucket/BitbucketSettings.java#L41) configurable.

If anyone want to do a pull request, we'll be happy to review !

Cheers

**Comment by sachingharge** [comment]
Hi again,

Just to update, one of my colleagues created a pull request to fix this.
Please review this: https://github.com/SonarQubeCommunity/sonar-auth-bitbucket/pull/9

**Comment by julienlancelot** [comment]
Thanks, PR has been applied
